backend:
  name: github
  repo: xiaoyuan8688/vericred
  branch: main
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: factory_info
    label: 厂家资料
    folder: "content/factory"
    create: true
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "详情文字", name: "body", widget: "markdown"}
      - {label: "配图", name: "photo", widget: "image"}
